// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOnAsPdqe1ATLekz5wghdqryxf_kEkSaI',
    appId: '1:660877873735:web:ac59b22d0e2e5cf2a19762',
    messagingSenderId: '660877873735',
    projectId: 'blood-donation-app-ntt-2-cef6f',
    authDomain: 'blood-donation-app-ntt-2-cef6f.firebaseapp.com',
    storageBucket: 'blood-donation-app-ntt-2-cef6f.firebasestorage.app',
    measurementId: 'G-96CDHV9MQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGG_3EtQw-D20JQvEV7tCRhzkjAtQaT6A',
    appId: '1:660877873735:android:ec5e9e0ed6b09a23a19762',
    messagingSenderId: '660877873735',
    projectId: 'blood-donation-app-ntt-2-cef6f',
    storageBucket: 'blood-donation-app-ntt-2-cef6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_VofWv0DrJmh6YpZqrWnAJnvYorw5OxQ',
    appId: '1:660877873735:ios:4eefcde6d02f38c8a19762',
    messagingSenderId: '660877873735',
    projectId: 'blood-donation-app-ntt-2-cef6f',
    storageBucket: 'blood-donation-app-ntt-2-cef6f.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_VofWv0DrJmh6YpZqrWnAJnvYorw5OxQ',
    appId: '1:660877873735:ios:4eefcde6d02f38c8a19762',
    messagingSenderId: '660877873735',
    projectId: 'blood-donation-app-ntt-2-cef6f',
    storageBucket: 'blood-donation-app-ntt-2-cef6f.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOnAsPdqe1ATLekz5wghdqryxf_kEkSaI',
    appId: '1:660877873735:web:bd08b0d1038eeef9a19762',
    messagingSenderId: '660877873735',
    projectId: 'blood-donation-app-ntt-2-cef6f',
    authDomain: 'blood-donation-app-ntt-2-cef6f.firebaseapp.com',
    storageBucket: 'blood-donation-app-ntt-2-cef6f.firebasestorage.app',
    measurementId: 'G-GMP35VD0FZ',
  );
}
