name: Build APK
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Cập nhật lên v4

      - name: Setup Java
        uses: actions/setup-java@v4 # Cập nhật lên v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release --split-per-abi
      
      - name: Upload APK
        uses: actions/upload-artifact@v4 # ĐÂY LÀ CHỖ QUAN TRỌNG NHẤT (Sửa v3 thành v4)
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk
